services:
  postgres:
    image: pgvector/pgvector:pg18
    restart: unless-stopped
    networks:
    - default
    volumes:
    - postgres-data:/var/lib/postgresql/data
    - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
    - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
  